version: '3.9'

services:
  postgres:
    image: postgres:14.3-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"